import time
import asyncio
import csv

import agents.main.agent as MainAgent
import agents.prediction.agent as PredictionAgent
from agents.prediction.helper import row_to_formatted_string

instructions = """   
        RESULTS REPORT:
                             
        Accuracy: 3/9
        
        Explanations generated by agent for correct predictions:
        1. The founder's elite education from a top-ranked institution combined with high market attractiveness and exit potential suggests a strong chance of success.
        2. The founder's elite education, proven track record with a >$500M IPO, and the high market exit potential make this a strong investment opportunity.
        3. The founder's elite education and extensive experience in a high-responsibility role align with the high exit potential historically seen in the Technology, Information & Internet Platforms sector.
        
        Explanations generated by agent for wrong predictions:
        1. The founder lacks direct entrepreneurial experience and there's no indication of a previous successful exit, signaling moderate entrepreneurial grit despite Elite education.
        2. The founder lacks both a track record of exits and deep domain expertise, combined with partial market fit and medium exit potential.
        3. The market exit potential is Medium to Low, and there is no strong signal from the founder's track record to counterbalance.
        4. The founder does not possess elite education, a previous exit, or deep domain expertise, and the market attractiveness was not conclusively shown to be high. Therefore, the profile does not strongly align with the success criteria.
        5. The founder lacks an elite education, significant track record, or deep domain expertise, and the market exit potential is medium to high but with challenges, which doesn't strongly justify a Yes given the current founder profile.
        6. The founder has no previous IPOs or acquisitions, and the market exit potential for Software Development in 2023 is not identified as High/Medium.
    """

if __name__ == "__main__":
    start = time.time()
    with open("data/train.csv", newline="", encoding="utf-8") as f_in:
        reader = csv.DictReader(f_in)
        rows = []
        actual = []
        for row in reader:
            rows.append(row_to_formatted_string(row))
            actual.append("1" == int(row.get("success")))
            if len(rows) >= 10:
                print(rows)
                results = asyncio.run(PredictionAgent.predictSuccess(rows))
                blocks = []
                cnt = 0
                for i, r in enumerate(results, 1):
                    cnt += int(r.prediction == actual[i-1])
                    block = [
                        f"Prediction {i}:",
                        f"Agent answer: {r.prediction}",
                        f"Correct answer: {actual[i-1]}"
                        f"Reasoning: {r.reason}",
                        f"Thought process: {', '.join(r.thought_process) if r.thought_process else '-'}",
                        ""
                    ]
                    blocks.append("\n".join(block))
                instructions = (f"REPORT:\n\nAccuracy: {cnt}/{10}") + ("\n".join(blocks))
                # asyncio.run(MainAgent.central(instructions))
                print(instructions)
                rows = []
                actual = []
                break

            

    # results = asyncio.run(MainAgent.central(instructions))
    # print(results)

    end = time.time()
    t = end - start

    print(f"Total run time: {t:.2f}s")