from agents.web_agent.main import findMCP
from agents.research_agent.main import researchMCP
from agents.main_agent.main import iterateMCP
import time
import asyncio

if __name__ == "__main__":
    start = time.time()
    asyncio.run(iterateMCP("""   
        TASK: Modify main.py, the instructions in main.py and mcp_agent.config.yaml of the prediction agent based on an evaluation of this report. You do not need my approval to make changes.

        RESULTS REPORT:
                             
        Accuracy: 2/10
        
        Explanations generated by agent for wrong predictions:
                           
        1. The founder shows strong domain expertise, having spent years working directly on the problem they're now solving. This significantly increases the odds of building something users actually need. However, their limited experience managing teams may slow execution as the company scales.

        2. The team's overall execution track record is solid, with previous products shipped and traction achieved in past roles. Still, the absence of any prior startup experience introduces uncertainty around navigating early-stage volatility.

        3. The founding team is well-balanced, combining technical depth with business development skills. This complementarity reduces early risks, though overlapping responsibilities between co-founders may create friction if roles aren't clarified.

        4. The founders appear highly motivated and mission-driven, signaling resilience and long-term commitment. At the same time, their tendency to overextend across too many initiatives could dilute focus during critical early milestones.

        5. Access to strong mentors and industry connections gives the startup a clear advantage, increasing the likelihood of faster customer validation. Yet, the team may become overly reliant on these networks rather than developing independent go-to-market capabilities.

        6. The founder demonstrates high learning velocity, adapting quickly to new information and iterating based on feedback—an encouraging sign for finding product-market fit. However, frequent pivots without sufficient testing could lead to strategic drift.

        7. Early traction suggests a promising problem-solution fit, backed by conversations with real users. Still, the current market hypothesis is unproven at scale, and the team will need to validate whether the demand extends beyond early adopters.

        8. The founder shows strong leadership qualities and an ability to attract early talent, which is critical for building momentum. But maintaining culture and alignment may prove challenging if rapid hiring occurs before foundational processes are in place.
    """))
    end = time.time()
    t = end - start

    print(f"Total run time: {t:.2f}s")